"""Add cancellation_policy_id and fee_amount to bookings

Revision ID: 6f0fec906ba2
Revises: 0280996151d9
Create Date: 2025-10-20 16:57:14.431322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0fec906ba2'
down_revision = '0280996151d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('cancellation_policy_id', sa.Integer(), nullable=True, comment='Cancellation policy applied to this booking'))
    op.add_column('bookings', sa.Column('cancellation_fee_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='Cancellation fee charged (BRL)'))
    op.create_index(op.f('ix_bookings_cancellation_policy_id'), 'bookings', ['cancellation_policy_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'cancellation_policies', ['cancellation_policy_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_cancellation_policy_id'), table_name='bookings')
    op.drop_column('bookings', 'cancellation_fee_amount')
    op.drop_column('bookings', 'cancellation_policy_id')
    # ### end Alembic commands ###
