"""Mako template for Alembic migrations."""

"""Add payment logs table

Revision ID: bc938920afad
Revises: 150034b64fa7
Create Date: 2025-10-20 14:30:43.420165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc938920afad'
down_revision = '150034b64fa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_logs',
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('refund_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_logs_booking_id', 'payment_logs', ['booking_id'], unique=False)
    op.create_index('idx_payment_logs_correlation_id', 'payment_logs', ['correlation_id'], unique=False)
    op.create_index('idx_payment_logs_level', 'payment_logs', ['level'], unique=False)
    op.create_index('idx_payment_logs_log_type', 'payment_logs', ['log_type'], unique=False)
    op.create_index('idx_payment_logs_payment_id', 'payment_logs', ['payment_id'], unique=False)
    op.create_index('idx_payment_logs_provider', 'payment_logs', ['provider'], unique=False)
    op.create_index('idx_payment_logs_provider_transaction_id', 'payment_logs', ['provider_transaction_id'], unique=False)
    op.create_index('idx_payment_logs_refund_id', 'payment_logs', ['refund_id'], unique=False)
    op.create_index('idx_payment_logs_timestamp', 'payment_logs', ['timestamp'], unique=False)
    op.create_index('idx_payment_logs_user_id', 'payment_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_logs_user_id', table_name='payment_logs')
    op.drop_index('idx_payment_logs_timestamp', table_name='payment_logs')
    op.drop_index('idx_payment_logs_refund_id', table_name='payment_logs')
    op.drop_index('idx_payment_logs_provider_transaction_id', table_name='payment_logs')
    op.drop_index('idx_payment_logs_provider', table_name='payment_logs')
    op.drop_index('idx_payment_logs_payment_id', table_name='payment_logs')
    op.drop_index('idx_payment_logs_log_type', table_name='payment_logs')
    op.drop_index('idx_payment_logs_level', table_name='payment_logs')
    op.drop_index('idx_payment_logs_correlation_id', table_name='payment_logs')
    op.drop_index('idx_payment_logs_booking_id', table_name='payment_logs')
    op.drop_table('payment_logs')
    # ### end Alembic commands ###
